import { z } from "zod";
import {
  SessionStatusSchema,
  PlanStepStatusSchema,
  PlanStatusSchema,
  ApprovalDecisionSchema,
  DisplayModeSchema,
  ChangeTypeSchema,
  AgentStatusSchema,
  ArtifactTypeSchema,
  RestoreTypeSchema,
  CommandStreamSchema,
  RiskLevelSchema,
  PermissionPolicySchema,
  EvidenceReferenceKindSchema,
  ContextReferenceTypeSchema,
} from "@codeforge/protocol";

export const SessionRecordSchema = z.object({
  id: z.string(),
  title: z.string(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  status: SessionStatusSchema,
  currentAgentId: z.string().optional(),
  currentModelId: z.string().optional(),
  currentProviderId: z.string().optional(),
  permissionMode: PermissionPolicySchema.optional(),
  displayMode: DisplayModeSchema.optional(),
  branch: z.string().optional(),
  workspacePath: z.string().optional(),
  taskTitle: z.string().optional(),
});
export type SessionRecord = z.infer<typeof SessionRecordSchema>;

export const TurnRecordSchema = z.object({
  id: z.string(),
  sessionId: z.string(),
  seq: z.number().int().nonnegative(),
  userMessage: z.string(),
  status: SessionStatusSchema,
  agentId: z.string().optional(),
  startedAt: z.string().datetime().optional(),
  completedAt: z.string().datetime().optional(),
  error: z.string().optional(),
});
export type TurnRecord = z.infer<typeof TurnRecordSchema>;

export const WorkItemSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("activity"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    title: z.string(),
    status: z.enum(["started", "completed", "failed"]),
    detail: z.string().optional(),
    expandedDetail: z.string().optional(),
    startedAt: z.string().datetime(),
    completedAt: z.string().datetime().optional(),
    durationMs: z.number().optional(),
  }),
  z.object({
    kind: z.literal("plan"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    title: z.string(),
    status: PlanStatusSchema,
    steps: z.array(
      z.object({
        id: z.string(),
        description: z.string(),
        status: PlanStepStatusSchema,
      }),
    ),
    comments: z
      .array(
        z.object({
          id: z.string(),
          stepId: z.string().optional(),
          text: z.string(),
          author: z.string(),
          createdAt: z.string().datetime(),
        }),
      )
      .optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("command"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    command: z.string(),
    workingDirectory: z.string().optional(),
    status: z.enum(["running", "completed", "failed"]),
    exitCode: z.number().optional(),
    durationMs: z.number().optional(),
    output: z.string().optional(),
    startedAt: z.string().datetime(),
    completedAt: z.string().datetime().optional(),
  }),
  z.object({
    kind: z.literal("file_change"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    path: z.string(),
    changeType: ChangeTypeSchema,
    additions: z.number(),
    deletions: z.number(),
    description: z.string().optional(),
    diff: z.string().optional(),
    comments: z
      .array(
        z.object({
          id: z.string(),
          line: z.number().optional(),
          text: z.string(),
          author: z.string(),
          createdAt: z.string().datetime(),
        }),
      )
      .optional(),
    appliedAt: z.string().datetime().optional(),
  }),
  z.object({
    kind: z.literal("approval"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    tool: z.string(),
    action: z.string(),
    description: z.string(),
    risk: RiskLevelSchema,
    scope: z.string().optional(),
    decision: ApprovalDecisionSchema.optional(),
    resolvedAt: z.string().datetime().optional(),
    createdAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("question"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    prompt: z.string(),
    options: z.array(z.string()).optional(),
    answer: z.string().optional(),
    resolvedAt: z.string().datetime().optional(),
    createdAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("artifact"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    type: ArtifactTypeSchema,
    title: z.string(),
    content: z.string().optional(),
    status: z.enum(["draft", "ready", "approved", "rejected"]),
    author: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("test_run"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    name: z.string(),
    passed: z.number(),
    failed: z.number(),
    skipped: z.number(),
    failures: z
      .array(
        z.object({
          test: z.string(),
          message: z.string(),
          stack: z.string().optional(),
        }),
      )
      .optional(),
    durationMs: z.number().optional(),
    startedAt: z.string().datetime(),
    completedAt: z.string().datetime().optional(),
  }),
  z.object({
    kind: z.literal("agent"),
    id: z.string(),
    sessionId: z.string(),
    role: z.string(),
    status: AgentStatusSchema,
    task: z.string(),
    parentAgentId: z.string().optional(),
    progress: z.number().min(0).max(100).optional(),
    modelId: z.string().optional(),
    providerId: z.string().optional(),
    startedAt: z.string().datetime(),
    completedAt: z.string().datetime().optional(),
  }),
  z.object({
    kind: z.literal("checkpoint"),
    id: z.string(),
    sessionId: z.string(),
    label: z.string(),
    ref: z.string().optional(),
    durableRef: z.string().optional(),
    commitSha: z.string().optional(),
    baseHead: z.string().optional(),
    branch: z.string().optional(),
    snapshotKind: z.enum(["git_clean", "git_stash"]).optional(),
    dirtyAtCreation: z.boolean().optional(),
    fileCount: z.number(),
    trackedPaths: z.array(z.string()).optional(),
    stagedPaths: z.array(z.string()).optional(),
    untrackedPaths: z.array(z.string()).optional(),
    testStatus: z.string().optional(),
    createdAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("evidence"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string().optional(),
    conclusion: z.string(),
    references: z.array(
      z.object({
        kind: EvidenceReferenceKindSchema,
        ref: z.string(),
      }),
    ),
    createdAt: z.string().datetime(),
  }),
  z.object({
    /**
     * Immutable, run-scoped evidence captured when an autonomous workflow reaches a terminal
     * decision. This is deliberately data-only: the renderer never resolves a filesystem path.
     */
    kind: z.literal("run_inspection"),
    id: z.string(),
    sessionId: z.string(),
    runId: z.string(),
    turnId: z.string(),
    executionMode: z.literal("agent"),
    taskTitle: z.string(),
    status: z.enum(["running", "completed", "blocked", "failed", "cancelled"]),
    phase: z.string(),
    workspace: z.object({
      id: z.string(),
      kind: z.enum(["local", "git-worktree"]),
      branch: z.string().optional(),
      checkpointId: z.string().optional(),
    }),
    diffs: z.array(z.object({
      path: z.string(),
      changeType: ChangeTypeSchema,
      additions: z.number().int().nonnegative(),
      deletions: z.number().int().nonnegative(),
      diff: z.string(),
      binary: z.boolean().optional(),
      beforeSize: z.number().int().nonnegative().optional(),
      afterSize: z.number().int().nonnegative().optional(),
      truncated: z.boolean().optional(),
    })),
    verificationAttempts: z.array(z.object({
      attempt: z.number().int().positive(),
      notConfigured: z.boolean(),
      passed: z.number().int().nonnegative(),
      failed: z.number().int().nonnegative(),
      skipped: z.number().int().nonnegative(),
      durationMs: z.number().nonnegative(),
      verifiers: z.array(z.object({
        id: z.string(),
        kind: z.enum(["test", "typecheck", "build", "lint", "custom"]),
        command: z.string(),
        required: z.boolean(),
        status: z.enum(["passed", "failed", "not_configured", "timed_out", "cancelled"]),
        passed: z.number().int().nonnegative(),
        failed: z.number().int().nonnegative(),
        skipped: z.number().int().nonnegative(),
        exitCode: z.number().int(),
        durationMs: z.number().nonnegative(),
        failureSummary: z.string().optional(),
      })),
    })),
    verification: z.object({
      planId: z.string(),
      policyVersion: z.string(),
      requiredCount: z.number().int().nonnegative(),
      satisfiedCount: z.number().int().nonnegative(),
      missingCount: z.number().int().nonnegative(),
      staleCount: z.number().int().nonnegative(),
      verificationComplete: z.boolean(),
      missingRequiredVerifiers: z.array(z.string()),
      evidence: z.array(z.object({
        evidenceId: z.string(),
        verifierId: z.string(),
        status: z.enum(["passed", "failed", "cancelled", "timed_out", "infra_error", "interrupted"]),
        durationMs: z.number().nonnegative(),
        outputTruncated: z.boolean(),
      })),
    }).optional(),
    repairs: z.array(z.object({
      attempt: z.number().int().positive(),
      summary: z.string(),
    })).default([]),
    review: z.object({
      approved: z.boolean(),
      findings: z.array(z.object({
        code: z.string(),
        severity: z.enum(["blocking", "advisory"]),
        path: z.string(),
        message: z.string(),
      })),
    }).optional(),
    completion: z.object({
      outcome: z.enum(["completed", "blocked", "failed"]),
      rationale: z.string(),
      blockers: z.array(z.object({ code: z.string(), severity: z.string(), message: z.string() })),
    }).optional(),
    provider: z.object({ providerId: z.string(), modelId: z.string() }).optional(),
    usage: z.object({
      inputTokens: z.number().int().nonnegative(),
      outputTokens: z.number().int().nonnegative(),
      totalTokens: z.number().int().nonnegative(),
    }).optional(),
    startedAt: z.string().datetime(),
    completedAt: z.string().datetime().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("context_ref"),
    id: z.string(),
    sessionId: z.string(),
    refType: ContextReferenceTypeSchema,
    ref: z.string(),
    label: z.string().optional(),
    addedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("workspace"),
    id: z.string(),
    sessionId: z.string().optional(),
    workspaceKind: z.enum(["local", "git-worktree"]),
    rootPath: z.string(),
    repositoryRoot: z.string(),
    gitCommonDir: z.string().optional(),
    branch: z.string().optional(),
    headSha: z.string().optional(),
    baseKind: z.enum(["head", "checkpoint"]).optional(),
    baseRef: z.string().optional(),
    checkpointId: z.string().optional(),
    parentWorkspaceId: z.string().optional(),
    status: z.enum(["ready", "locked", "retained_dirty", "orphaned", "released", "cleaned", "missing"]),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("autonomous_run"),
    id: z.string(),
    sessionId: z.string().optional(),
    workspaceId: z.string(),
    goal: z.string(),
    status: z.enum([
      "created",
      "exploring",
      "planning",
      "executing",
      "reviewing",
      "revising",
      "verifying",
      "integration_ready",
      "integrating",
      "completed",
      "blocked",
      "cancelled",
      "failed",
    ]),
    baseRevision: z.string(),
    finalRevision: z.string().optional(),
    checkpointId: z.string().optional(),
    isolatedWorktreeId: z.string().optional(),
    isolatedBranch: z.string().optional(),
    startedAt: z.string().datetime().optional(),
    completedAt: z.string().datetime().optional(),
    reviewRounds: z.number().int().nonnegative().optional(),
    taskGraphJson: z.string().optional(),
    resultJson: z.string().optional(),
    error: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("parallel_run"),
    id: z.string(),
    sessionId: z.string(),
    workspaceId: z.string(),
    goal: z.string(),
    status: z.enum(["created", "planning", "executing", "synthesizing", "reviewing", "verifying", "integrating", "completed", "blocked", "cancelled", "failed"]),
    baseRevision: z.string(),
    planJson: z.string().optional(),
    workstreamsJson: z.string().optional(),
    contractsJson: z.string().optional(),
    synthesisJson: z.string().optional(),
    promotionJson: z.string().optional(),
    verificationCommandsJson: z.string().optional(),
    usageJson: z.string().optional(),
    cleanupCompletedAt: z.string().datetime().optional(),
    error: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("mission"),
    id: z.string(),
    sessionId: z.string(),
    workspaceId: z.string(),
    goal: z.string(),
    status: z.enum(["created", "analyzing", "planning", "executing", "evaluating", "replanning", "paused", "blocked", "cancelled", "failed", "completed"]),
    baseRevision: z.string(),
    currentPlanVersion: z.number().int().nonnegative(),
    currentWave: z.number().int().nonnegative(),
    missionJson: z.string().optional(),
    error: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("change_delivery"),
    id: z.string(),
    sessionId: z.string(),
    missionId: z.string(),
    workspaceId: z.string(),
    status: z.enum(["created", "analyzing", "packaging", "reviewing", "verifying", "ready", "blocked", "cancelled", "failed"]),
    sourceRevision: z.string(),
    targetRevision: z.string(),
    deliveryJson: z.string().optional(),
    error: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("remote_publication"),
    id: z.string(),
    sessionId: z.string(),
    deliveryId: z.string(),
    workspaceId: z.string(),
    status: z.enum(["local_ready", "remote_authorized", "validating_remote", "publishing_branch", "creating_pr", "remote_pr_ready", "blocked", "failed", "cancelled", "remote_diverged", "authorization_required"]),
    publicationJson: z.string().optional(),
    error: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    // CF-11B: the Cloud-authoritative publication record mirrored for local display. Desktop never
    // writes an outcome here that Cloud did not report.
    kind: z.literal("cloud_publication"),
    id: z.string(),
    sessionId: z.string(),
    deliveryId: z.string(),
    workspaceId: z.string(),
    status: z.enum([
      "identity_required",
      "authorization_required",
      "authorization_pending",
      "preparing",
      "awaiting_artifact",
      "artifact_uploaded",
      "validating",
      "validated",
      "waiting_for_lease",
      "authorizing",
      "checking_target",
      "pushing",
      "pushed",
      "creating_pr",
      "pr_created",
      "completed",
      "failed_retryable",
      "failed_permanent",
      "authorization_revoked",
      "target_diverged",
    ]),
    cloudPublicationId: z.string().optional(),
    publicationJson: z.string().optional(),
    error: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("agent_model_turn"),
    id: z.string(),
    sessionId: z.string().optional(),
    runId: z.string(),
    agentId: z.string(),
    turnId: z.string(),
    state: z.enum(["created", "provider_request_started", "provider_response_completed", "tool_requests_decoded", "agent_result_completed", "failed", "cancelled"]),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("agent_turn_recovery"),
    id: z.string(),
    sessionId: z.string(),
    turnId: z.string(),
    originalStatus: z.enum(["running", "paused", "waiting_for_approval", "waiting_for_question", "recovering"]),
    state: z.enum(["hydrated", "replan_required", "replan_started", "resumed", "blocked"]),
    generation: z.number().int().positive(),
    staleExecutionCount: z.number().int().nonnegative(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
    detail: z.string().optional(),
  }),
  z.object({
    kind: z.literal("agent_tool_execution"),
    id: z.string(),
    sessionId: z.string().optional(),
    runId: z.string(),
    agentId: z.string(),
    turnId: z.string(),
    toolName: z.string(),
    argumentsHash: z.string(),
    executionClass: z.enum(["read_only", "write", "command", "network"]),
    state: z.enum(["requested", "started", "completed", "observation_recorded", "failed", "cancelled"]),
    recoveryDisposition: z.enum(["safe_to_retry", "requires_revalidation", "already_completed", "unknown_side_effect", "blocked"]),
    startedAt: z.string().datetime().optional(),
    completedAt: z.string().datetime().optional(),
    resultHash: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("verification"),
    id: z.string(),
    sessionId: z.string(),
    runId: z.string(),
    recordType: z.enum(["plan", "attempt", "evidence"]),
    planId: z.string(),
    verifierId: z.string().optional(),
    status: z.string().optional(),
    payload: z.record(z.unknown()),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("user_intent_hold"),
    id: z.string(),
    sessionId: z.string(),
    runId: z.string(),
    turnId: z.string().optional(),
    state: z.enum(["running", "user_intent_hold", "steer_queued", "reconciling_steer"]),
    reason: z.enum(["user_composer_active", "user_steer_queued", "awaiting_inflight_completion", "draft_cleared", "user_intent_hold_disabled", "reconciled", "stale_lease"]),
    generation: z.number().int().positive(),
    enteredAt: z.string().datetime().optional(),
    releasedAt: z.string().datetime().optional(),
    checkpoint: z.object({
      runId: z.string(),
      workItemId: z.string().optional(),
      currentPlanStep: z.string().optional(),
      completedSteps: z.array(z.string()),
      pendingSteps: z.array(z.string()),
      activeExecution: z.object({ executionId: z.string(), kind: z.enum(["tool", "verifier", "subagent", "model", "other"]) }).optional(),
      workspaceGeneration: z.number().int().nonnegative(),
      stateHash: z.string().optional(),
      enteredAt: z.string().datetime(),
      reason: z.literal("user_intent_hold"),
    }).optional(),
    queuedSteers: z.array(z.object({
      steerId: z.string(),
      turnId: z.string(),
      message: z.string(),
      submittedAt: z.string().datetime(),
    })),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
  z.object({
    kind: z.literal("steer_receipt"),
    id: z.string(),
    sessionId: z.string(),
    steerId: z.string(),
    turnId: z.string(),
    /** CF-17R5 targeted parallel steering: the workstream this steer is scoped to. Absent = an
     * ordinary session/turn-level steer, unaffected by any parallel work item. */
    targetWorkstreamId: z.string().optional(),
    message: z.string(),
    consumedAt: z.string().datetime().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
]);
export type WorkItem = z.infer<typeof WorkItemSchema>;
export type WorkItemKind = WorkItem["kind"];

export const isWorkItem = (value: unknown): value is WorkItem =>
  WorkItemSchema.safeParse(value).success;

export const isWorkItemKind = <K extends WorkItem["kind"]>(item: WorkItem, kind: K): item is Extract<WorkItem, { kind: K }> =>
  item.kind === kind;
