/**
 * CF-11B canonical publication error contract.
 *
 * Every code here is stable and machine-readable, and every code is safe to return to a client:
 * nothing derived from a token, a Git subprocess, or a GitHub response body may become a message.
 */
export const PUBLICATION_ERROR_CODES = {
  // Authorization
  UNAUTHENTICATED: "UNAUTHENTICATED",
  REPOSITORY_NOT_AUTHORIZED: "REPOSITORY_NOT_AUTHORIZED",
  INSTALLATION_REVOKED: "INSTALLATION_REVOKED",
  AUTHORIZATION_STATE_INVALID: "AUTHORIZATION_STATE_INVALID",
  AUTHORIZATION_STATE_EXPIRED: "AUTHORIZATION_STATE_EXPIRED",
  AUTHORIZATION_STATE_REPLAYED: "AUTHORIZATION_STATE_REPLAYED",
  AUTHORIZATION_USER_MISMATCH: "AUTHORIZATION_USER_MISMATCH",
  INSTALLATION_OWNED_BY_OTHER_USER: "INSTALLATION_OWNED_BY_OTHER_USER",
  INSTALLATION_NOT_FOUND: "INSTALLATION_NOT_FOUND",

  // Ownership / lifecycle
  PUBLICATION_NOT_FOUND: "PUBLICATION_NOT_FOUND",
  PUBLICATION_OWNERSHIP_VIOLATION: "PUBLICATION_OWNERSHIP_VIOLATION",
  PUBLICATION_IDEMPOTENCY_CONFLICT: "PUBLICATION_IDEMPOTENCY_CONFLICT",
  PUBLICATION_STATE_INVALID: "PUBLICATION_STATE_INVALID",
  PUBLICATION_NOT_RETRYABLE: "PUBLICATION_NOT_RETRYABLE",

  // Artifact
  ARTIFACT_TOO_LARGE: "ARTIFACT_TOO_LARGE",
  ARTIFACT_LENGTH_MISMATCH: "ARTIFACT_LENGTH_MISMATCH",
  ARTIFACT_DIGEST_MISMATCH: "ARTIFACT_DIGEST_MISMATCH",
  ARTIFACT_ALREADY_STORED: "ARTIFACT_ALREADY_STORED",
  ARTIFACT_MISSING: "ARTIFACT_MISSING",
  ARTIFACT_INVALID_BUNDLE: "ARTIFACT_INVALID_BUNDLE",
  ARTIFACT_STORAGE_PATH_INVALID: "ARTIFACT_STORAGE_PATH_INVALID",

  // Materialization
  CERTIFIED_COMMIT_MISMATCH: "CERTIFIED_COMMIT_MISMATCH",
  CERTIFIED_TREE_MISMATCH: "CERTIFIED_TREE_MISMATCH",
  TARGET_COMMIT_MISSING: "TARGET_COMMIT_MISSING",
  ANCESTRY_MISMATCH: "ANCESTRY_MISMATCH",
  ARTIFACT_METADATA_MISMATCH: "ARTIFACT_METADATA_MISMATCH",
  REF_NAME_INVALID: "REF_NAME_INVALID",

  // Remote target
  PROMOTION_TARGET_DIVERGED: "PROMOTION_TARGET_DIVERGED",

  // Execution ownership
  PUBLICATION_LEASE_UNAVAILABLE: "PUBLICATION_LEASE_UNAVAILABLE",
  PUBLICATION_LEASE_STALE: "PUBLICATION_LEASE_STALE",

  // Remote transport
  GITHUB_AUTH_FAILED: "GITHUB_AUTH_FAILED",
  GITHUB_TEMPORARY_FAILURE: "GITHUB_TEMPORARY_FAILURE",
  GIT_PUSH_REJECTED: "GIT_PUSH_REJECTED",
  PUBLICATION_REF_CONFLICT: "PUBLICATION_REF_CONFLICT",
  PULL_REQUEST_RECONCILIATION_FAILED: "PULL_REQUEST_RECONCILIATION_FAILED",
} as const;

export type PublicationErrorCode = (typeof PUBLICATION_ERROR_CODES)[keyof typeof PUBLICATION_ERROR_CODES];

/** Codes whose cause can plausibly clear on its own; everything else is permanent. */
const RETRYABLE: ReadonlySet<string> = new Set<PublicationErrorCode>([
  PUBLICATION_ERROR_CODES.GITHUB_TEMPORARY_FAILURE,
  PUBLICATION_ERROR_CODES.PUBLICATION_LEASE_UNAVAILABLE,
  PUBLICATION_ERROR_CODES.PUBLICATION_LEASE_STALE,
  PUBLICATION_ERROR_CODES.GIT_PUSH_REJECTED,
  PUBLICATION_ERROR_CODES.PULL_REQUEST_RECONCILIATION_FAILED,
]);

export class PublicationError extends Error {
  constructor(readonly code: PublicationErrorCode, readonly httpStatus = 400) {
    // The code IS the message: no upstream text is ever interpolated.
    super(code);
    this.name = "PublicationError";
  }

  get retryable(): boolean {
    return RETRYABLE.has(this.code);
  }
}

export function isPublicationErrorCode(value: unknown): value is PublicationErrorCode {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(PUBLICATION_ERROR_CODES, value);
}

export function publicationErrorStatus(code: PublicationErrorCode): number {
  switch (code) {
    case PUBLICATION_ERROR_CODES.UNAUTHENTICATED:
      return 401;
    case PUBLICATION_ERROR_CODES.PUBLICATION_NOT_FOUND:
      return 404;
    case PUBLICATION_ERROR_CODES.PUBLICATION_OWNERSHIP_VIOLATION:
    case PUBLICATION_ERROR_CODES.REPOSITORY_NOT_AUTHORIZED:
    case PUBLICATION_ERROR_CODES.INSTALLATION_REVOKED:
    case PUBLICATION_ERROR_CODES.INSTALLATION_OWNED_BY_OTHER_USER:
    case PUBLICATION_ERROR_CODES.AUTHORIZATION_USER_MISMATCH:
      return 403;
    case PUBLICATION_ERROR_CODES.PUBLICATION_IDEMPOTENCY_CONFLICT:
    case PUBLICATION_ERROR_CODES.ARTIFACT_ALREADY_STORED:
    case PUBLICATION_ERROR_CODES.PUBLICATION_LEASE_UNAVAILABLE:
    case PUBLICATION_ERROR_CODES.PUBLICATION_REF_CONFLICT:
      return 409;
    case PUBLICATION_ERROR_CODES.ARTIFACT_TOO_LARGE:
      return 413;
    case PUBLICATION_ERROR_CODES.GITHUB_TEMPORARY_FAILURE:
      return 503;
    default:
      return 400;
  }
}
