import React from "react";
import { resolveAssetUrlByName } from "./emoji-assets.js";
import { resolveEightBitStatusAsset, type EightBitStatusPayload } from "./eight-bit-status.js";

export interface EightBitStatusBadgeProps {
  status: EightBitStatusPayload | undefined;
}

/**
 * Minimal, compact 8-Bit routing status indicator. Renders nothing when there is no status
 * to show (not an error). The emoji is decorative (`alt=""`, `aria-hidden`); `accessibleText`
 * — generated by the backend from the actual routing decision, never re-derived here — is the
 * real content, exposed via `role="status" aria-live="polite"` so the status is understandable
 * with images disabled. Emoji rendering can never affect this component's runtime behavior:
 * an unrecognized event still renders the fallback asset and the same accessible text.
 */
export function EightBitStatusBadge({ status }: EightBitStatusBadgeProps) {
  if (!status) return null;
  const assetName = resolveEightBitStatusAsset(status.event);
  return (
    <div className="eight-bit-status-badge" role="status" aria-live="polite" data-eight-bit-event={status.event}>
      <img src={resolveAssetUrlByName(assetName)} width={20} height={20} alt="" aria-hidden="true" draggable={false} />
      <span className="eight-bit-status-text">{status.accessibleText}</span>
    </div>
  );
}

export default EightBitStatusBadge;
