import crypto from "node:crypto";
import { FORGE_GREEN_CACHE_SCHEMA_VERSION } from "./canonical-cache.js";
import { FORGE_GREEN_POLICY_VERSION, FORGE_GREEN_FEATURE_VERSION } from "./constants.js";

/**
 * FG-1E ForgeGreen efficiency ledger.
 *
 * The ledger is observational only. It never grants a permission, resolves an approval,
 * waives verification, or contributes to a completion decision. Savings claims are honest:
 * every event carries an accuracy classification — `measured` (provider/deterministically
 * attributable), `estimated` (bounded heuristic), or `unknown` (detected but not quantifiable).
 * Events carry operational quantities, identities, hashes, and reason codes only — never
 * secret material, prompt text, conversation history, reasoning, or raw tool output.
 */

export type EfficiencyMeasurement = "measured" | "estimated" | "unknown";

export type ForgeGreenMechanism =
  | "provider_prompt_cache"
  | "local_prompt_prefix_cache"
  | "tool_output_compression"
  | "duplicate_suppression"
  | "no_progress_interruption"
  | "canonical_analysis_cache"
  | "context_reuse"
  | "request_dedupe"
  | "fallback"
  | "repository_intelligence"
  | "verification_coverage"
  | "risk_analysis"
  | "model_failover"
  | "verification_policy"
  | "evidence_resolution";

export interface EfficiencyLedgerEvent {
  mechanism: ForgeGreenMechanism;
  measurement: EfficiencyMeasurement;
  quantity?: number;
  unit?: "bytes" | "tokens" | "count";
  /** Short reason code; never free-form content. */
  reason?: string;
}

export interface ForgeGreenLedgerTotals {
  bytesAvoidedMeasured: number;
  tokensAvoidedMeasured: number;
  eventsWithUnknownQuantity: number;
  duplicateActionsSuppressed: number;
  noProgressInterruptions: number;
  canonicalCacheHits: number;
  canonicalCacheMisses: number;
  canonicalCacheInvalidations: number;
  avoidedModelRequests: number;
  avoidedToolDispatches: number;
  fallbackEvents: number;
  /** FG-2: files reparsed by repository intelligence (work done). */
  repositoryFilesReparsed: number;
  /** FG-2: files whose persisted intelligence was reused without reparsing (work avoided). */
  repositoryFilesReused: number;
  /** FG-2: content-addressed parse-cache hits inside repository intelligence. */
  repositoryParseCacheHits: number;
  /** FG-2: dependents re-resolved because a resolved dependency target was deleted. */
  repositoryInvalidations: number;
  /** 8-Bit: cross-provider/model rotations performed during an active run. */
  modelFailoverRotations: number;
  /** 8-Bit: routing decisions that stopped short of a paid/unknown-cost dispatch because no
   * eligible free route existed (NO_ELIGIBLE_FREE_MODEL) — evidence of the free boundary
   * holding, not a savings claim. */
  modelFailoverBlockedDispatches: number;
  /** FG-3D: Context Pages served from the persistent cross-session/cross-worktree page cache
   * without recomputing from RepositoryIntelligence (work avoided). */
  contextPagesReused: number;
  /** FG-3D: Context Pages freshly built from RepositoryIntelligence this run (work done). */
  contextPagesPulled: number;
  /** FG-4: deterministic structural-risk analyses performed. */
  riskAnalyses: number;
  /** FG-4: structural-risk results served from the canonical cache. */
  riskCacheHits: number;
  /** FG-4: structural-risk cache misses/recomputations. */
  riskCacheMisses: number;
  /** FG-4: advisory capability escalations recommended by structural evidence. */
  riskRoleEscalations: number;
  /** FG-4: advisory context breadth expansions recommended by structural evidence. */
  riskContextExpansions: number;
  /** FG-5: verification obligations generated by verification policy. */
  verificationObligationsGenerated: number;
  /** FG-5: verification policy decisions served from canonical cache. */
  verificationCacheHits: number;
  /** FG-5: valid un-stale verification evidence reused without execution. */
  verificationEvidenceReused: number;
  /** FG-5: targeted test suites selected (V1/V2/V3) instead of full-system suites. */
  verificationTargetedSuitesUsed: number;
  /** FG-5: full-system/monorepo suites safely avoided when narrower verification was sufficient. */
  verificationFullSuitesAvoided: number;
  /** FG-5: full-system/monorepo suites required due to systemic risk or uncertainty. */
  verificationFullSuitesRequired: number;
  /** FG-5: stale or incompatible verification evidence rejected. */
  verificationStaleEvidenceRejected: number;
  /** FG-5: redundant reruns avoided due to current valid evidence. */
  verificationRerunsAvoided: number;
  /** FG-5: verification blocked events (missing infra, unapproved commands, etc.). */
  verificationBlockedEvents: number;
  /** FG-6: verification obligations received by evidence resolver. */
  resolutionObligationsReceived: number;
  /** FG-6: exact duplicate obligations removed. */
  resolutionDuplicatesRemoved: number;
  /** FG-6: verification obligations subsumed by broader evidence. */
  resolutionObligationsSubsumed: number;
  /** FG-6: existing valid verification evidence reused. */
  resolutionEvidenceReused: number;
  /** FG-6: new verification evidence producers scheduled. */
  resolutionProducersScheduled: number;
  /** FG-6: redundant verification dispatches avoided. */
  resolutionDispatchesAvoided: number;
  /** FG-6: evidence resolution plans served from canonical cache. */
  resolutionCacheHits: number;
  /** FG-6: evidence resolution plans recomputed on cache miss. */
  resolutionCacheMisses: number;
}

export interface ForgeGreenLedgerIdentity {
  runId: string;
  operation: string;
  namespace: string;
  sessionId?: string;
  agentId?: string;
  turnId?: string;
  executionRevision?: string;
  workstreamScope?: string;
  policyVersion?: string;
  featureVersion?: string;
}

export interface ForgeGreenLedgerRecord {
  ledgerSchemaVersion: string;
  ledgerId: string;
  identity: ForgeGreenLedgerIdentity;
  events: EfficiencyLedgerEvent[];
  totals: ForgeGreenLedgerTotals;
  policyVersion: string;
  featureVersion: string;
  createdAt: string;
}

export const FORGE_GREEN_LEDGER_SCHEMA_VERSION = FORGE_GREEN_CACHE_SCHEMA_VERSION;

function emptyTotals(): ForgeGreenLedgerTotals {
  return {
    bytesAvoidedMeasured: 0,
    tokensAvoidedMeasured: 0,
    eventsWithUnknownQuantity: 0,
    duplicateActionsSuppressed: 0,
    noProgressInterruptions: 0,
    canonicalCacheHits: 0,
    canonicalCacheMisses: 0,
    canonicalCacheInvalidations: 0,
    avoidedModelRequests: 0,
    avoidedToolDispatches: 0,
    fallbackEvents: 0,
    repositoryFilesReparsed: 0,
    repositoryFilesReused: 0,
    repositoryParseCacheHits: 0,
    repositoryInvalidations: 0,
    modelFailoverRotations: 0,
    modelFailoverBlockedDispatches: 0,
    contextPagesReused: 0,
    contextPagesPulled: 0,
    riskAnalyses: 0,
    riskCacheHits: 0,
    riskCacheMisses: 0,
    riskRoleEscalations: 0,
    riskContextExpansions: 0,
    verificationObligationsGenerated: 0,
    verificationCacheHits: 0,
    verificationEvidenceReused: 0,
    verificationTargetedSuitesUsed: 0,
    verificationFullSuitesAvoided: 0,
    verificationFullSuitesRequired: 0,
    verificationStaleEvidenceRejected: 0,
    verificationRerunsAvoided: 0,
    verificationBlockedEvents: 0,
    resolutionObligationsReceived: 0,
    resolutionDuplicatesRemoved: 0,
    resolutionObligationsSubsumed: 0,
    resolutionEvidenceReused: 0,
    resolutionProducersScheduled: 0,
    resolutionDispatchesAvoided: 0,
    resolutionCacheHits: 0,
    resolutionCacheMisses: 0,
  };
}

function clampQuantity(quantity: number | undefined): number {
  return typeof quantity === "number" && Number.isFinite(quantity) && quantity > 0 ? Math.floor(quantity) : 0;
}

export class ForgeGreenLedgerCollector {
  private readonly events: EfficiencyLedgerEvent[] = [];
  private readonly totals = emptyTotals();

  constructor(private readonly identity: ForgeGreenLedgerIdentity) {}

  record(event: EfficiencyLedgerEvent): void {
    this.events.push(event);
    const quantity = clampQuantity(event.quantity);
    switch (event.mechanism) {
      case "provider_prompt_cache":
      case "local_prompt_prefix_cache":
        if (event.measurement === "measured" && event.unit === "tokens") this.tokensAvoidedMeasured(quantity);
        else if (event.measurement === "unknown") this.noteUnknown();
        break;
      case "tool_output_compression":
        if (event.unit === "bytes") this.totals.bytesAvoidedMeasured += quantity;
        else if (event.measurement === "unknown") this.noteUnknown();
        break;
      case "duplicate_suppression":
        this.totals.duplicateActionsSuppressed += 1;
        this.totals.avoidedToolDispatches += 1;
        break;
      case "no_progress_interruption":
        this.totals.noProgressInterruptions += 1;
        break;
      case "canonical_analysis_cache":
        if (event.reason === "hit") this.totals.canonicalCacheHits += 1;
        else if (event.reason === "miss") this.totals.canonicalCacheMisses += 1;
        else if (event.reason?.startsWith("invalidated")) this.totals.canonicalCacheInvalidations += 1;
        break;
      case "request_dedupe":
        this.totals.avoidedModelRequests += 1;
        break;
      case "context_reuse":
        if (event.reason === "page_reused") this.totals.contextPagesReused += quantity;
        else if (event.reason === "page_pulled") this.totals.contextPagesPulled += quantity;
        else if (event.measurement === "measured" && event.unit === "tokens") this.tokensAvoidedMeasured(quantity);
        else if (event.measurement === "unknown") this.noteUnknown();
        break;
      case "fallback":
        this.totals.fallbackEvents += 1;
        break;
      case "repository_intelligence":
        if (event.reason === "files_parsed") this.totals.repositoryFilesReparsed += quantity;
        else if (event.reason === "files_reused") this.totals.repositoryFilesReused += quantity;
        else if (event.reason === "parse_cache_hits") this.totals.repositoryParseCacheHits += quantity;
        else if (event.reason === "dependent_revalidation") this.totals.repositoryInvalidations += quantity;
        else if (event.measurement === "unknown") this.noteUnknown();
        break;
      case "risk_analysis":
        if (event.reason === "analysis") this.totals.riskAnalyses += quantity;
        else if (event.reason === "cache_hit") this.totals.riskCacheHits += quantity;
        else if (event.reason === "cache_miss") this.totals.riskCacheMisses += quantity;
        else if (event.reason === "role_escalation") this.totals.riskRoleEscalations += quantity;
        else if (event.reason === "context_expansion") this.totals.riskContextExpansions += quantity;
        break;
      case "model_failover":
        if (event.reason === "rotated") this.totals.modelFailoverRotations += 1;
        else if (event.reason === "no_eligible_route") this.totals.modelFailoverBlockedDispatches += 1;
        break;
      case "verification_policy":
        if (event.reason === "obligations_generated") this.totals.verificationObligationsGenerated += quantity;
        else if (event.reason === "cache_hit") this.totals.verificationCacheHits += quantity;
        else if (event.reason === "evidence_reused") this.totals.verificationEvidenceReused += quantity;
        else if (event.reason === "targeted_suite_used") this.totals.verificationTargetedSuitesUsed += quantity;
        else if (event.reason === "full_suite_avoided") this.totals.verificationFullSuitesAvoided += quantity;
        else if (event.reason === "full_suite_required") this.totals.verificationFullSuitesRequired += quantity;
        else if (event.reason === "stale_rejected") this.totals.verificationStaleEvidenceRejected += quantity;
        else if (event.reason === "rerun_avoided") this.totals.verificationRerunsAvoided += quantity;
        else if (event.reason === "blocked") this.totals.verificationBlockedEvents += quantity;
        break;
      case "evidence_resolution":
        if (event.reason === "obligations_received") this.totals.resolutionObligationsReceived += quantity;
        else if (event.reason === "duplicates_removed") this.totals.resolutionDuplicatesRemoved += quantity;
        else if (event.reason === "obligations_subsumed") this.totals.resolutionObligationsSubsumed += quantity;
        else if (event.reason === "evidence_reused") this.totals.resolutionEvidenceReused += quantity;
        else if (event.reason === "producers_scheduled") this.totals.resolutionProducersScheduled += quantity;
        else if (event.reason === "dispatches_avoided") this.totals.resolutionDispatchesAvoided += quantity;
        else if (event.reason === "cache_hit") this.totals.resolutionCacheHits += quantity;
        else if (event.reason === "cache_miss") this.totals.resolutionCacheMisses += quantity;
        break;
    }
  }

  private tokensAvoidedMeasured(quantity: number): void {
    this.totals.tokensAvoidedMeasured += quantity;
  }

  private noteUnknown(): void {
    this.totals.eventsWithUnknownQuantity += 1;
  }

  recordToolCompression(originalBytes: number, compressedBytes: number, applied: boolean): void {
    if (!applied) return;
    this.record({ mechanism: "tool_output_compression", measurement: "measured", quantity: Math.max(0, originalBytes - compressedBytes), unit: "bytes" });
  }

  recordProviderPromptCache(cachedInputTokens?: number, cacheWriteTokens?: number): void {
    if (typeof cachedInputTokens === "number" && cachedInputTokens > 0) {
      this.record({ mechanism: "provider_prompt_cache", measurement: "measured", quantity: cachedInputTokens, unit: "tokens", reason: "provider_reported" });
    } else {
      this.record({ mechanism: "provider_prompt_cache", measurement: "unknown", reason: typeof cacheWriteTokens === "number" && cacheWriteTokens > 0 ? "cache_write_only" : "telemetry_absent" });
    }
  }

  recordDuplicateSuppressed(): void {
    this.record({ mechanism: "duplicate_suppression", measurement: "measured", quantity: 1, unit: "count", reason: "identical_read_unchanged_state" });
  }

  recordNoProgressInterruption(reason: string): void {
    this.record({ mechanism: "no_progress_interruption", measurement: "measured", quantity: 1, unit: "count", reason: reason.slice(0, 120) });
  }

  recordCanonicalCacheHit(): void {
    this.record({ mechanism: "canonical_analysis_cache", measurement: "measured", quantity: 1, unit: "count", reason: "hit" });
  }

  recordCanonicalCacheMiss(): void {
    this.record({ mechanism: "canonical_analysis_cache", measurement: "measured", quantity: 1, unit: "count", reason: "miss" });
  }

  recordCanonicalCacheInvalidation(reason: string): void {
    this.record({ mechanism: "canonical_analysis_cache", measurement: "measured", quantity: 1, unit: "count", reason: `invalidated:${reason.slice(0, 80)}` });
  }

  /** FG-2: observational repository-analysis metrics from the latest refresh or full index. */
  recordRepositoryRefresh(metrics: { filesParsed: number; filesReused: number; parseCacheHits: number; invalidations: number }): void {
    if (metrics.filesParsed > 0) this.record({ mechanism: "repository_intelligence", measurement: "measured", quantity: metrics.filesParsed, unit: "count", reason: "files_parsed" });
    if (metrics.filesReused > 0) this.record({ mechanism: "repository_intelligence", measurement: "measured", quantity: metrics.filesReused, unit: "count", reason: "files_reused" });
    if (metrics.parseCacheHits > 0) this.record({ mechanism: "repository_intelligence", measurement: "measured", quantity: metrics.parseCacheHits, unit: "count", reason: "parse_cache_hits" });
    if (metrics.invalidations > 0) this.record({ mechanism: "repository_intelligence", measurement: "measured", quantity: metrics.invalidations, unit: "count", reason: "dependent_revalidation" });
  }

  recordRequestDeduped(): void {
    this.record({ mechanism: "request_dedupe", measurement: "measured", quantity: 1, unit: "count", reason: "in_flight_or_completed_match" });
  }

  recordFallback(reason: string): void {
    this.record({ mechanism: "fallback", measurement: "measured", quantity: 1, unit: "count", reason: reason.slice(0, 120) });
  }

  /** 8-Bit: a cross-provider/model rotation actually occurred during an active run. */
  recordModelFailoverRotation(): void {
    this.record({ mechanism: "model_failover", measurement: "measured", quantity: 1, unit: "count", reason: "rotated" });
  }

  /** 8-Bit: routing correctly refused to dispatch because no free-eligible route existed
   * (the free-policy boundary holding under pressure — observational, not a savings claim). */
  recordModelFailoverBlocked(): void {
    this.record({ mechanism: "model_failover", measurement: "measured", quantity: 1, unit: "count", reason: "no_eligible_route" });
  }

  /** FG-3D: Context Pages served from the persistent page cache this run (a count, not an
   * estimate — a page either hit the cache or it did not). */
  recordContextPagesReused(count: number): void {
    if (count > 0) this.record({ mechanism: "context_reuse", measurement: "measured", quantity: count, unit: "count", reason: "page_reused" });
  }

  /** FG-3D: Context Pages freshly built (not reused) this run. */
  recordContextPagesPulled(count: number): void {
    if (count > 0) this.record({ mechanism: "context_reuse", measurement: "measured", quantity: count, unit: "count", reason: "page_pulled" });
  }

  /** FG-5: verification obligations generated by verification policy. */
  recordVerificationObligations(count: number): void {
    if (count > 0) this.record({ mechanism: "verification_policy", measurement: "measured", quantity: count, unit: "count", reason: "obligations_generated" });
  }

  /** FG-5: verification policy decision cache hit. */
  recordVerificationCacheHit(): void {
    this.record({ mechanism: "verification_policy", measurement: "measured", quantity: 1, unit: "count", reason: "cache_hit" });
  }

  /** FG-5: valid un-stale verification evidence reused without re-running. */
  recordVerificationEvidenceReused(count: number): void {
    if (count > 0) this.record({ mechanism: "verification_policy", measurement: "measured", quantity: count, unit: "count", reason: "evidence_reused" });
  }

  /** FG-5: targeted test suite (V1/V2/V3) selected instead of full monorepo suite. */
  recordVerificationTargetedSuiteUsed(): void {
    this.record({ mechanism: "verification_policy", measurement: "measured", quantity: 1, unit: "count", reason: "targeted_suite_used" });
  }

  /** FG-5: full-system suite safely avoided because narrow verification was sufficient. */
  recordVerificationFullSuiteAvoided(): void {
    this.record({ mechanism: "verification_policy", measurement: "measured", quantity: 1, unit: "count", reason: "full_suite_avoided" });
  }

  /** FG-5: full-system suite required due to high structural risk or uncertainty. */
  recordVerificationFullSuiteRequired(): void {
    this.record({ mechanism: "verification_policy", measurement: "measured", quantity: 1, unit: "count", reason: "full_suite_required" });
  }

  /** FG-5: stale or invalid verification evidence rejected. */
  recordVerificationStaleRejected(count = 1): void {
    if (count > 0) this.record({ mechanism: "verification_policy", measurement: "measured", quantity: count, unit: "count", reason: "stale_rejected" });
  }

  /** FG-5: redundant reruns avoided due to valid un-stale evidence. */
  recordVerificationRerunAvoided(count = 1): void {
    if (count > 0) this.record({ mechanism: "verification_policy", measurement: "measured", quantity: count, unit: "count", reason: "rerun_avoided" });
  }

  /** FG-5: verification blocked event recorded. */
  recordVerificationBlocked(): void {
    this.record({ mechanism: "verification_policy", measurement: "measured", quantity: 1, unit: "count", reason: "blocked" });
  }

  snapshot(): ForgeGreenLedgerRecord {
    const createdAt = new Date().toISOString();
    const record = {
      ledgerSchemaVersion: FORGE_GREEN_LEDGER_SCHEMA_VERSION,
      identity: this.identity,
      events: [...this.events],
      totals: { ...this.totals },
      policyVersion: this.identity.policyVersion ?? FORGE_GREEN_POLICY_VERSION,
      featureVersion: this.identity.featureVersion ?? FORGE_GREEN_FEATURE_VERSION,
      createdAt,
    };
    const ledgerId = crypto.createHash("sha256").update(JSON.stringify(record)).digest("hex").slice(0, 24);
    return { ledgerId, ...record };
  }
}

export function createForgeGreenLedgerCollector(identity: ForgeGreenLedgerIdentity): ForgeGreenLedgerCollector {
  return new ForgeGreenLedgerCollector(identity);
}
